### ISSUE TITLE
Too many errors, can't compile/debug

### ISSUE THREAD

**Issue by dragitz** [the-dargon-project/the-dargon-project#30]
Here's the pic http://i.imgur.com/uwoSvgN.png

'Haelp plz'

**Comment by miyu** [comment]
Commit https://github.com/the-dargon-project/the-dargon-project/commit/12dc90e3af8e38bfe2425bafbbec83f25896f692 should fix the Dargon.Services bug - had pushed a change that referenced a local project rather than a nuget package.

Addressed test build issues with https://github.com/the-dargon-project/the-dargon-project/commit/80240676610014940180334652c598d4028ee7b6 though it seems VS2015 has a (documented online) bug that makes c++ unit tests not work - @RichieSams, maybe it's time to update to gtest or something?

detours.h issues: Need to install Microsoft Detours sdk (presumably http://research.microsoft.com/en-us/projects/detours/, though might need the previous major version) to C:/detours so that `C:/detours/lib` exists.

**Comment by dragitz** [comment]
Thank you sir

**Comment by dragitz** [comment]
So, http://i.imgur.com/1pNuNzF.png

**Comment by miyu** [comment]
Did you properly set up detours?

**Comment by RichieSams** [comment]
I had problems with VS tests with my other project as well. GTest is
extremely easy to set up and the testing API is similar / almost identical
to most of the other APIs. It's also heavily documented.

I'd be willing to do the refactor. (should be no more than a weekend)

**Comment by dragitz** [comment]
I'm not a good programmer and I'm not into vb, is there an already compiled version that I can download?

**Comment by miyu** [comment]
Hey dragitz, we're working quickly towards shipping and will probably have a beta build up in the next week or two. If you're talking about detours - that comes with an include and lib directory.

**Comment by dragitz** [comment]
Thank you all, I'll wait (:

Keep the amazing work

**Comment by miyu** [comment]
+1
